
#ifndef AUTO_GENERATED_SHARED_OR_STATIC_LIB1_EXPORTS_HPP
#define AUTO_GENERATED_SHARED_OR_STATIC_LIB1_EXPORTS_HPP

#ifdef TARGETSHAREDORSTATICLIB1_STATIC_DEFINE
#  define SHARED_OR_STATIC_LIB1_API
#  define TARGETSHAREDORSTATICLIB1_NO_EXPORT
#else
#  ifndef SHARED_OR_STATIC_LIB1_API
#    ifdef targetSharedOrStaticLib1_EXPORTS
        /* We are building this library */
#      define SHARED_OR_STATIC_LIB1_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define SHARED_OR_STATIC_LIB1_API __declspec(dllimport)
#    endif
#  endif

#  ifndef TARGETSHAREDORSTATICLIB1_NO_EXPORT
#    define TARGETSHAREDORSTATICLIB1_NO_EXPORT 
#  endif
#endif

#ifndef TARGETSHAREDORSTATICLIB1_DEPRECATED
#  define TARGETSHAREDORSTATICLIB1_DEPRECATED __declspec(deprecated)
#endif

#ifndef TARGETSHAREDORSTATICLIB1_DEPRECATED_EXPORT
#  define TARGETSHAREDORSTATICLIB1_DEPRECATED_EXPORT SHARED_OR_STATIC_LIB1_API TARGETSHAREDORSTATICLIB1_DEPRECATED
#endif

#ifndef TARGETSHAREDORSTATICLIB1_DEPRECATED_NO_EXPORT
#  define TARGETSHAREDORSTATICLIB1_DEPRECATED_NO_EXPORT TARGETSHAREDORSTATICLIB1_NO_EXPORT TARGETSHAREDORSTATICLIB1_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TARGETSHAREDORSTATICLIB1_NO_DEPRECATED
#    define TARGETSHAREDORSTATICLIB1_NO_DEPRECATED
#  endif
#endif

#endif /* AUTO_GENERATED_SHARED_OR_STATIC_LIB1_EXPORTS_HPP */
