#pragma once
#include "AutoGeneratedSharedOrStaticLib1Exports.hpp"

namespace Code::SharedOrStaticLib1
{

SHARED_OR_STATIC_LIB1_API void SharedOrStaticLib1Api();

} // ~namespace Code::SharedOrStaticLib1
