#pragma once
#include "AutoGeneratedSharedOrStaticLib3Exports.hpp"

namespace Code::SharedOrStaticLib3
{

SHARED_OR_STATIC_LIB3_API void SharedOrStaticLib3Api();

} // ~namespace Code::SharedOrStaticLib3
