
#ifndef AUTO_GENERATED_SHARED_OR_STATIC_LIB2_EXPORTS_HPP
#define AUTO_GENERATED_SHARED_OR_STATIC_LIB2_EXPORTS_HPP

#ifdef TARGETSHAREDORSTATICLIB2_STATIC_DEFINE
#  define SHARED_OR_STATIC_LIB2_API
#  define TARGETSHAREDORSTATICLIB2_NO_EXPORT
#else
#  ifndef SHARED_OR_STATIC_LIB2_API
#    ifdef targetSharedOrStaticLib2_EXPORTS
        /* We are building this library */
#      define SHARED_OR_STATIC_LIB2_API __declspec(dllexport)
#    else
        /* We are using this library */
#      define SHARED_OR_STATIC_LIB2_API __declspec(dllimport)
#    endif
#  endif

#  ifndef TARGETSHAREDORSTATICLIB2_NO_EXPORT
#    define TARGETSHAREDORSTATICLIB2_NO_EXPORT 
#  endif
#endif

#ifndef TARGETSHAREDORSTATICLIB2_DEPRECATED
#  define TARGETSHAREDORSTATICLIB2_DEPRECATED __declspec(deprecated)
#endif

#ifndef TARGETSHAREDORSTATICLIB2_DEPRECATED_EXPORT
#  define TARGETSHAREDORSTATICLIB2_DEPRECATED_EXPORT SHARED_OR_STATIC_LIB2_API TARGETSHAREDORSTATICLIB2_DEPRECATED
#endif

#ifndef TARGETSHAREDORSTATICLIB2_DEPRECATED_NO_EXPORT
#  define TARGETSHAREDORSTATICLIB2_DEPRECATED_NO_EXPORT TARGETSHAREDORSTATICLIB2_NO_EXPORT TARGETSHAREDORSTATICLIB2_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef TARGETSHAREDORSTATICLIB2_NO_DEPRECATED
#    define TARGETSHAREDORSTATICLIB2_NO_DEPRECATED
#  endif
#endif

#endif /* AUTO_GENERATED_SHARED_OR_STATIC_LIB2_EXPORTS_HPP */
