#pragma once
#include "AutoGeneratedSharedOrStaticLib2Exports.hpp"

namespace Code::SharedOrStaticLib2
{

SHARED_OR_STATIC_LIB2_API void SharedOrStaticLib2Api();

} // ~namespace Code::SharedOrStaticLib2
